config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#welcome'
  get 'story', to:'pages#story'
  get 'ceremony_reception', to:'pages#ceremony_reception'
  get 'registries', to:'pages#registries'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def ceremony_reception
  end

  def story
  end

  def registries
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weddingsite</title>
    <%= csrf_meta_tags %>
    <!-- Custom import of Google Font 'Alegreya'-->
    <link href="//fonts.googleapis.com/css?family=Alegreya:400,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Bootstrap navigation bar -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container-fluid'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav">
            <!-- Ruby way of creating links -->
            <li><%= link_to "WELCOME", root_path %></li>
            <li><%= link_to "CEREMONY ∞ RECEPTION", ceremony_reception_path %></li>
            <li><%= link_to "OUR STORY", story_path %></li>
            <li><%= link_to "REGISTRIES", registries_path %></li>
            <!-- HTML way of creating links -->
            <!-- <li><a href="/">WELCOME</a></li> -->
            <!-- <li><a href="/">CEREMONY / RECEPTION</a></li> -->
            <!-- <li><a href="/story">OUR STORY</a></li> -->
            <!-- <li><a href="/">REGISTRIES</a></li> -->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>


    <%= yield %>

  </body>
</html>

app/views/pages/ceremony_reception.html.erb
<div class="ceremony_reception-callout text-center container-fluid">
  <h1>CEREMONY ∞ RECEPTION</h1>
</div>

app/views/pages/registries.html.erb
<div class="registries-callout text-center container-fluid">
  <h1>REGISTRIES</h1>
  <p><br>As we start our journey together, we're going to need abuncha stuff!<br><br>
    Here are some options we picked out that would best prepare us for our adventure (besides lightsabers).<br>
  </p>
</div>

app/views/pages/story.html.erb
<div class="story-callout text-center container-fluid">
  <h1>OUR STORY</h1>
</div>

app/views/pages/welcome.html.erb
<div class="welcome-callout text-center container-fluid">
  <div class="our-names">
    <Header>KRIZIA ∞ GEORGE</Header>
  </div>
  <h3>December 9, 2017</h3>
</div>